project/project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include('register.urls')),
    path('putup/', include('putup.urls', namespace="putup")),
    # include関数によりアプリケーション側のurls.pyと連結する。
    # 引数はアプリケーションフォルダ内のurls.py
    # https://qiita.com/taole33/items/9a09b7bce0ee455d266f

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/putup/urls.py
from django.urls import path
from . import views

app_name = 'putup'

urlpatterns = [
    path('', views.item, name='item'),
    path('detail/<int:putup_id>/', views.detail, name='detail'),
    path('new/',views.new, name='new'),
]

  # path(URL,関数 or class,name=templateやviewで使うURL名称)

project/putup/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Item(models.Model):
    ITEM_CONDITION = (
        ('新品','新品'),
        ('新古品','新古品'),
        ('良中古品','良中古品'),
        ('悪中古品','悪中古品'),
        ('ジャンク品','ジャンク品'),
    )
    
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="出品者名")
    title = models.CharField(max_length=200, blank=False, verbose_name="商品名")
    description = models.TextField(max_length=2000, verbose_name="商品説明")
    image = models.ImageField(upload_to='images/',blank=True, null=True, verbose_name="商品画像")
    # MEDIA_URLで指定したパスとuploads_toで指定したパスが連結してパスが生成される(/media/images)
    start_price = models.PositiveIntegerField(default=0, verbose_name="開始価格")
    condition = models.CharField(max_length=20, choices=ITEM_CONDITION, verbose_name="商品状態")
    created_date = models.DateTimeField(default=timezone.now, verbose_name="出品日")
    # https://office54.net/python/django/model-field-options

    class Meta:
        # https://note.com/saito_pythonista/n/n2d02442ea1bf#jPuMt
        verbose_name = "商品"
        verbose_name_plural = verbose_name
        
    def created(self):
        self.created_date = timezone.now()
        self.save()
        
    def __str__(self):
        return self.title
    # 管理画面上のタイトルの判別が可能となる
    # https://office54.net/python/django/model-str-self

project/putup/forms.py
from django import forms
from .models import Item

class PutupForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ('title', 'description', 'image', 'start_price', 'condition')

project/putup/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.views import generic
from .forms import PutupForm
from .models import Item


def item(request):
    items = Item.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
    return render(request, 'putup/item.html/', {'items': items})

    # https://office54.net/python/django/views-render-how-to
    # render => request=セッション情報+requestの種類(get/post), template_name=表示するhtml, context=htmlに渡したいデータの集合

def detail(request, putup_id):
    detail = get_object_or_404(Item ,pk=putup_id)
    return render(request, 'putup/detail.html', {'detail': detail})

def new(request):
    if request.method == "POST":
        form = PutupForm(request.POST, request.FILES)
        if form.is_valid():
        # formに入力された値にエラーがないかバリデートする
        # https://teratail.com/questions/116711
            putup = form.save(commit=False)
            putup.seller = request.user
            putup.created_date = timezone.now()
            putup.save()
            return redirect('putup:item')
            # https://qiita.com/taole33/items/9a09b7bce0ee455d266f
    else:
        form = PutupForm()
    return render(request, 'putup/edit.html', {'form':form})
    フォームを保存

project/putup/templates/putup/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    
    <title>オークションサイト</title>
  </head>
  <body>
    
{% if user.is_authenticated %}
    <div>
        <a href="{% url 'putup:new' %}">投稿</a>
        <h1><a href="{% url 'putup:item' %}">オークションサイト</a></h1>
      </div>
      
      <div>
        {% block content %}
        {% endblock %}
      </div>
{% endif %}
  </body>
</html>

project/putup/templates/putup/detail.html
{% extends 'putup/base.html' %}

{% block content %}
      <div>
        <h3>タイトル：{{ detail.title }}</h3>
          <p>出品日:{{ detail.created_date }}</p>
          <p>出品者：{{ detail.seller }}</p>
          <p>商品説明：{{ detail.description }}</p>
          {% if detail.image %}
          <p>商品画像：<img src="{{ detail.image.url }}"/></p>
          {% endif %}
          <p>開始価格：{{ detail.start_price }}円</p>
          <p>商品状態：{{ detail.condition }}</p>
      </div>
{% endblock %}

project/putup/templates/putup/edit.html
{% extends 'putup/base.html' %}

{% block content %}
  <div>
    <h3>出品フォーム</h3>
    <form method="POST">{% csrf_token %}
      <!-- https://blog.senseshare.jp/csrf.html -->
      {{ form.as_p }}
      <button type="submit">投稿</button>
    </form>
  </div>

{% endblock %}

project/putup/templates/putup/item.html
{% extends 'putup/base.html' %}

{% block content %}
  {% for item in items %}
      <div>
        <h2><a href="{% url 'putup:detail' item.id %}">タイトル：{{ item.title }}</a></h2>
        <p>出品者：{{ item.seller }}</p>
        <p>商品説明：{{ item.description }}</p>
        <p>開始価格：{{ item.start_price }}円</p>
        <p>商品状態：{{ item.condition|linebreaksbr }}</p>
      </div>
  {% endfor %}

{% endblock %}